<div id="view-content">
	<style type="text/css">
		.category_box {
			padding: 10px;
			margin: 5px;
			float: left;
			width: 215px;
			border: 1px solid #D0D0D0;
		}

		.category_box img {
			width: 24px;
			height: 24px;
			margin-right: 5px;
		}

		.category_box h3 {
			margin-bottom: 5px;
		}

		.category_box ul {
			list-style: none;
			margin-left: 10px;
		}
	</style>
	<?php
	foreach($this -> mainCategories as $mainCategory): ?>
	<?php if(is_array($this -> subCategories[$mainCategory -> ID]) && !empty($this -> subCategories[$mainCategory -> ID])): ?>
		<?php $temp = array_chunk($this -> subCategories[$mainCategory -> ID], 8); ?>
		<?php foreach($temp as $part => $catPart): ?>
		<div class="category_box">
			<h3>
				<img src="<?php echo $this -> baseUrl(file_exists('images/ico/' . $mainCategory -> ID . '.gif') ? '/images/ico/' . $mainCategory -> ID . '.gif' : '/imgs/default.png'); ?>">
				<a href="<?php echo $this -> url(array('controller'=>'search', 'action' => 'index')) . '?cat=' . $mainCategory -> ID; ?>"><?php echo $mainCategory -> name; if($part != 0) echo ' cd.'; ?></a>
			</h3>
			<ul>
			<?php foreach($catPart as $category): ?>
				<li><a href="<?php echo $this -> url(array('controller'=>'search', 'action' => 'index')) . '?cat=' . $category -> ID; ?>"><?php echo $category -> name; ?></a></li>
			<?php endforeach; ?>
			</ul>
		</div>
		<?php endforeach; ?>
	<?php endif; ?>
	<?php endforeach; ?>
</div>