<div id="view-content">
	<?php
		if(isset($this -> message)) echo $this -> message;
		if(!$this -> onlyMessage) {
			$newPassword = new Zend_Form_Element_Password('new_password');
			$newPassword -> setLabel('Nowe hasło:');
			$newPasswordConfirm = new Zend_Form_Element_Password('new_password_confirm');
			$newPasswordConfirm -> setLabel('Potwierdz:');
			$form = new Zend_Form();
			$form -> setAction($this -> url(array('controller' => 'account', 'action' => 'change_lost_password')) . '?key=' . $_GET['key']) -> setMethod('post');
			$form -> addElement($newPassword);
			$form -> addElement($newPasswordConfirm);
			$form -> addElement('submit', 'Zmień hasło');
			echo $form -> render();
		}
	?>
</div>
