<div id="view-content">
	<?php
		$oldPassword = new Zend_Form_Element_Password('old_password');
		$oldPassword -> setLabel('Stare hasło:');
		$newPassword = new Zend_Form_Element_Password('new_password');
		$newPassword -> setLabel('Nowe hasło:');
		$newPasswordConfirm = new Zend_Form_Element_Password('new_password_confirm');
		$newPasswordConfirm -> setLabel('Potwierdz:');
		$form = new Zend_Form();
		$form -> setAction('/account/change_password') -> setMethod('post');
		$form -> addElement($oldPassword);
		$form -> addElement($newPassword);
		$form -> addElement($newPasswordConfirm);
		$form -> addElement('submit', 'Zmień hasło');
		if(isset($this -> message)) echo $this -> message;
		echo $form -> render();
	?>
</div>