<div id="view-content">
	<?php
		if(isset($this -> message)) echo $this -> message;
		if($this -> displayForm) {
			$newPassword = new Zend_Form_Element_Password('newPassword');
			$newPassword -> setLabel('Nowe hasło:');
			$newPasswordConfirm = new Zend_Form_Element_Password('newPasswordConfirm');
			$newPasswordConfirm -> setLabel('Potwierdz:');
			$form = new Zend_Form();
			$form -> setAction('/account/change_lost_password?key=' . $_GET['key']) -> setMethod('post');
			$form -> addElement($newPassword);
			$form -> addElement($newPasswordConfirm);
			$form -> addElement('submit', 'Zmień hasło');
			echo $form -> render();
		}
	?>
</div>