<div id="view-content">
	<?php
		if(isset($this -> message)) echo $this -> message;
		$form = new Zend_Form();
		$form -> setAction($this -> url(array('controller' => 'account', 'action' => 'lost_password'))) -> setMethod('post');
		$username = new Zend_Form_Element_Text('username');
		$username -> setLabel('Login:');
		$form -> addElement($username);
		$form -> addElement('submit', 'Odzyskaj');
		echo $form -> render();
	?>
</div>
