<div id="view-content">
	<?php
		$username = new Zend_Form_Element_Text('username');
		$username -> setLabel('Login:');
		$form = new Zend_Form();
		$form -> setAction($this->url(array('controller'=>'account', 'action'=>'lost_password'))) -> setMethod('post');
		$form -> addElement($username);
		$form -> addElement('submit', 'Odzyskaj');
		if(isset($this -> message)) echo $this -> message;
		echo $form -> render();
	?>
	<?php if(isset($this -> key)): ?>
	<a href="<?php echo $this -> url(array('controller' => 'account', 'action' => 'change_lost_password')) . '?key=' . $this -> key; ?>">Zmień hasło</a>
	<?php endif; ?>
</div>
