<div id="view-content">
	<?php
		if(isset($this -> message)) echo $this -> message;
		if(!$this -> onlyMessage) {
			$form = new Zend_Form();
			$form -> setAction($this->url(array('controller'=>'account', 'action'=>'register'))) -> setMethod('post');
			$username = new Zend_Form_Element_Text('username');
			$username -> setLabel('Login:');
			if(isset($_POST['username'])) $username -> setValue($_POST['username']);
			$form -> addElement($username);
			$email = new Zend_Form_Element_Text('email');
			$email -> setLabel('Email:');
			if(isset($_POST['email'])) $email -> setValue($_POST['email']);
			$form -> addElement($email);
			$password = new Zend_Form_Element_Password('password');
			$password -> setLabel('Hasło:');
			$form -> addElement($password);
			$passwordConfirm = new Zend_Form_Element_Password('password_confirm');
			$passwordConfirm -> setLabel('Potwierdź hasło:');
			$form -> addElement($passwordConfirm);
			$form -> addElement('submit', 'Zarejestruj');
			echo $form -> render();
		}
	?>
</div>
