<div id="ann_create_content">
<?php
	$this->stylesheets = array('announcement_create.css');

	echo '<h1>';
	switch($this->stage)
	{	
		case 0:
			echo 'Krok 1.: wybierz kategorię';
			break;
		
		case 1:
			echo 'Krok 2.: uzupełnij treść ogłoszenia';
			break;
		
		case 2:
			echo 'Krok 3.: załaduj zdjęcia';
			break;
		
		case 3:
			echo 'Gratulacje! Dodałeś ogłoszenie.';
			break;
	}
	echo '</h1>';
?>

<form method="post" enctype="multipart/form-data" action="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'create')); ?>">
	<?php if($this->stage == 0): ?>
		Wybierz kategorię: <select name="catID">
		<?php
			foreach($this->categories as $catid1 => $cat1)
			{
				if(is_null($cat1->parentID))
				{
					echo '<optgroup label="' . $cat1->name . '">';
					
					foreach($this->categories as $catid2 => $cat2)
					{
						if($cat2->parentID == $catid1)
							echo '<option value="' . $catid2 . '">' . $cat2->name . '</option>';
					}
					
					echo '</optgroup>';
				}
			}
		?>
		</select>
		<input type="submit" value="Dalej" />
	<?php endif; ?>

	<?php if($this->stage == 1): ?>
		<input type="hidden" name="catID" value="<?php echo $_POST['catID'] ?>" />

		<label for="ann_title">Tytuł ogłoszenia: </label>
		<input type="text" name="title" id="ann_title" value="<?php echo (isset($_POST['title']) ? $_POST['title'] : '' ); ?>" />

		<br /><label for="ann_content">Treść ogłoszenia:</label>
		<br /><textarea name="content" rows="15" cols="60" id="ann_content"><?php echo (isset($_POST['content']) ? $_POST['content'] : '' ); ?></textarea>

		<?php
			foreach($this->attributes as $att)
			{
				switch($att->type)
				{
					case '0':
					case '1':
					case '4':
						echo '<br /><label for="att' . $att->ID . '">' . $att->name . ': </label>' .
							'<input type="text" id="att' . $att->ID . '" name="' . $att->ID . '" value="' .
							(isset($_POST[$att->ID]) ? $_POST[$att->ID] : '' ) . '" />';
						break;
					
					case '2':
						echo '<br /><label for="att' . $att->ID . '">' . $att->name . ': </label>' .
							'<select id="att' . $att->ID . '" name="' . $att->ID . '">';
						echo '<option value="">Nieokreślone</option>';
						foreach($att->options as $oid => $oname)
							echo '<option value="' . $oid . '"' . 
								(isset($_POST[$att->ID]) && $_POST[$att->ID] == $oid ? ' selected' : '' ) . '>' .
								$oname . '</option>';
						echo '</select>';
						break;
					
					case '3':
						echo '<br /><input type="checkbox" id="att' . $att->ID . '" value="1" name="' . $att->ID . '"' .
							(isset($_POST[$att->ID]) ? ' checked' : '') . ' />' .
							'<label for="att' . $att->ID . '"> ' . $att->name . '</label>';
						break;
				}
			}
		?>

		<br /><input type="submit" value="Dalej" /><br />
		
		<?php foreach($this->messages as $msg) echo $msg . '<br />'; ?>
	<?php endif; ?>
	
	<?php if($this->stage == 2): ?>
		<input type="hidden" name="catID" value="<?php echo $_POST['catID'] ?>" />
		<input type="hidden" name="title" value="<?php echo $_POST['title'] ?>" />
		<input type="hidden" name="content" value="<?php echo $_POST['content'] ?>" />
		<?php
			foreach($_POST as $key => $value)
			{
				if(preg_match('/^[0-9]+$/', $key) && $value != '')
					echo sprintf('<input type="hidden" name="%s" value="%s" />', $key, $value);
			}
		?>
			
		<?php foreach($images as $id => $name): ?>
			<input type="hidden" name="images[<? echo $id; ?>]" value="<?php echo $name; ?>" />
			<div class="image">
				<div class="image_wrapper_outer"><div class="image_wrapper">
					<img src="<?php echo $this->baseUrl('images/' . $name); ?>" />
				</div></div>
				<input type="checkbox" name="images_to_delete[]" value="<?php echo $id; ?>" id="imgdel<?php echo $id; ?>" />
				<label for="imgdel<?php echo $id; ?>"> Usuń obrazek</label>
			</div>
		<?php endforeach; ?>
		
		<?php if(count($images) > 0) echo '<input type="submit" value="Wykonaj" />'; ?>
		
		<br /><br />
		<label for="uploadInput">Wybierz pliki zdjęć: </label>
		<input type="hidden" name="MAX_FILE_SIZE" value="500000" />
		<input type="file" name="uploaded[]" id="uploadInput" multiple />
		<br /><input type="submit" value="Wykonaj" />
		<br /><br /><input type="submit" name="finish" value="Gotowe" />
	<?php endif; ?>
</form>
</div>
