<div id="view-content">
	<?php echo $this -> message; ?>
	<?php if(!$this -> onlyMessage): ?>
		<div>
			<?php echo $this -> announcement -> title; ?><br>
			-----------------<br>
			<?php echo $this -> announcement -> content; ?><br>
			--------------<br>
			by user with id: <?php echo $this -> announcement -> userID === null ? 'Anonymous' : $this -> announcement -> userID; ?>
			<?php echo date('d-m-Y H:i:s', $this -> announcement -> date); ?><br>
			<?php if(is_array($this -> announcement -> images)):
			foreach($this -> announcement -> images as $image): ?>
				<a href="<?php echo $this->baseUrl('imgs/' . $image); ?>">
				<img src="<?php echo $this->baseUrl('imgs/' . $image); ?>" style="max-width: 250px; max-height: 250px;" />
				</a>
			<?php endforeach; endif; ?>
		</div>
	<?php endif; ?>
</div>
