<?php /*
	Elementy layoutu (właściwości obiektu view):
		- siteTitle - tytuł strony, dodawany po myślniku do "Ogłoszenia" (np. "Ogłoszenia - konto użytkownika")
		- stylesheets - tablica nazw dodatkowych plików css (muszą być w folderze public/css), potrzebnych danemu widokowi (np. array('account.css', 'foo.css'))
		- scripts - jak wyżej, tyle że pliki z kodem JavaScript. Muszą być w folderze public/js
		- footerContent - treść do wyświetlenia w stopce (nie mam jeszcze pomysłu co powinno się tam znaleźć :>)
		
		Prócz tego oczywiście wyświetlana jest zawartość widoku.
*/ ?>

<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Ogłoszenia <?php if(isset($this -> siteTitle)) echo '- ' . $this -> siteTitle; ?></title>
		<link rel="stylesheet" type="text/css" href="<?php echo $this -> baseUrl('css/main.css'); ?>" />
		<script type="text/javascript" src="<?php echo $this -> baseUrl('js/main.js'); ?>"></script>
	
		<?php if(is_array($this -> stylesheets)): foreach($this -> stylesheets as $stylesheet): ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this -> baseUrl('css/' . $stylesheet); ?>" />
		<?php endforeach; endif; ?>
	
		<?php if(is_array($this -> scripts)): foreach($this -> scripts as $script): ?>
		<script type="text/javascript" src="<?php echo $this -> baseUrl('js/' . $script); ?>"></script>
		<?php endforeach; endif; ?>
	</head>
	<body>
		<div id="main">
			<div id="header">
				<a href="<?php echo $this -> url(array('controller' => 'index', 'action' => 'index')); ?>">Ogłoszenia</a>
			</div>
			<div id="bar">
				<div id="bar_top">
					<ul>
						<li class="tab"><a href="<?php echo $this -> url(array('controller' => 'index', 'action' => 'index')); ?>">Strona główna</a></li>
						<li class="tab"><a href="<?php echo $this -> url(array('controller' => 'announcement', 'action' => 'create')); ?>">Dodaj ogłoszenie</a></li>
						<?php if(Zend_Registry::get('userModel') -> isLoggedIn()): ?>
						<li class="tab"><a href="<?php echo $this -> url(array('controller' => 'watchlist', 'action' => 'index')); ?>">Obserwowane</a></li>
						<?php endif; ?>
						<?php echo $this -> userMenu(); ?>
					</ul>
				</div>
				<div id="bar_bottom"></div>
			</div>
			<?php if(!$this -> searchPage): ?>
			<div id="search_bar">
				<form action="<?php echo $this -> url(array('controller' => 'search', 'action' => 'index')); ?>" method="GET">
					<label for="keywords">Wyszukaj ogłoszenie: </label><input name="keywords" type="text" value="">
					<?php //temporary solution
					$catMapper = new Application_Model_CategoriesMapper();
					$categories = $catMapper -> getAll();
					$elStr = '<select name="cat"><option value="all"' . ($_GET['cat'] == 'all' ? ' selected' : '') . '>Wszystkie</option>';
					foreach($categories as $ckey => $cat)
					{
						if(is_null($cat->parentID))
						{
							$elStr .= sprintf('<optgroup label="%s">', $cat -> name);
					
							foreach($categories as $chckey => $chcat)
							{
								if($chcat->parentID == $ckey)
								{
									$elStr .= sprintf('<option value="%s"%s>%s</option>',
											$chckey,
											($chckey == $_GET['cat'] ? ' selected' : ''),
											$chcat->name);
								}
							}
					
							$elStr .= '</optgroup>';
						}
					}
					$elStr .= '</select>';
					echo $elStr;
					?>
					<input name="send" type="submit" value="Szukaj">
				</form>
			</div>
			<?php endif; ?>
			<div id="body">
				<div id="sidebar">
					<?php if($this -> searchPage): ?>
					<h2 id="sidebar_title">Szukaj:</h2>
					<?php echo $this -> searchForm(); ?>
					<br>
					<?php endif; ?>
					<div class="advert_place">Miejsce na twoją reklamę!</div>
					<div class="advert_place">Miejsce na twoją reklamę!</div>
				</div>
				<div id="content">
					<?php echo $this -> layout() -> content; ?>
				</div>
			</div>
			<div id="footer">
				<?php echo $this -> footerContent; ?>
			</div>
		</div>
	</body>
</html>
