<?php
	if(isset($this->message))
		echo $this->message;

	$this->stylesheets = array('search.css');
?>



<?php if(count($this->anns) == 0): ?>
Żadne ogłoszenia nie pasują do podanych kryteriów.
<?php else: ?>
<h2>Wyniki wyszukiwania:</h2>
<?php foreach($this->anns as $announcement): ?>
<div class="announcement">
	<div class="ann_img_wrapper"><div class="ann_img">
		<img src="<?php echo $this->baseUrl('imgs/' . (count($announcement->images) ? reset($announcement->images) : 'default.png')); ?>" />
	</div></div>
	<h1><a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'index')) . '?id=' . $announcement->ID; ?>"><?php echo $announcement->title; ?></a></h1>
	<?php if(is_array($this -> atts)): ?>
	<div class="ann_attributes">
		<?php
		foreach($this -> atts as $att) {
			if($att -> main == '1' && isset($announcement -> attributes[$att -> ID])) {
				echo '<div class="ann_attribute">' .
				$att -> name . ': ' . ($att -> type != 2 ? $announcement -> attributes[$att -> ID] : $att -> options[$announcement -> attributes[$att -> ID]]) . ($att -> unit != '' ? ' ' . $att -> unit : '').
				'</div> ';
			}
		}
		?>
	</div>
	<?php endif; ?>
	<div class="ann_content">
		<?php echo strlen($announcement->content) > 255 ? substr(strip_tags($announcement->content), 0, 255) . '...' : $announcement->content; ?>
	</div>
	<div class="ann_links"><a href="<?php echo $this -> url(array('controller' => 'watchlist', 'action' => 'add')) . '?id=' . $announcement -> ID; ?>">Dodaj do obserwowanych</a>
		<?php if($announcement->userID == Zend_Registry::get('userModel')->getUserID()): ?>
		| <a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'edit')) . '?id=' . $announcement->ID; ?>">Edytuj</a>
		| <a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'delete')) . '?id=' . $announcement->ID; ?>">Usuń</a>
		<?php elseif(Zend_Registry::get('userModel')->isAdmin()): ?>
		| <a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'delete')) . '?id=' . $announcement->ID; ?>">Usuń</a>
		<?php endif; ?>
	</div>
</div>
<?php endforeach; endif; ?>

<?php if(count($this->anns) != 0) echo $this->pageSwitcher(); ?>
