<?php
	if(isset($this->message))
		echo $this->message;
	
	$this->stylesheets = array('search.css');
?>

<?php echo $this->pageSwitcher(); ?>

<?php if(count($this->anns) == 0): ?>
Żadne ogłoszenia nie pasują do podanych kryteriów.
<?php else: foreach($this->anns as $announcement): ?>
<div class="announcement">
	<div class="ann_img_wrapper"><div class="ann_img">
		<img src="<?php echo $this->baseUrl('imgs/' . (count($announcement->images) ? reset($announcement->images) : 'default.png')); ?>" />
	</div></div>
	<h1><a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'index')) . '?id=' . $announcement->ID; ?>"><?php echo $announcement->title; ?></a></h1>
	<a href="<?php echo $this -> url(array('controller' => 'watchlist', 'action' => 'add')) . '?id=' . $announcement -> ID; ?>">Dodaj do obserwowanych</a>
	<?php if($announcement->userID == Zend_Registry::get('userModel')->getUserID()): ?>
	| <a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'edit')) . '?id=' . $announcement->ID; ?>">Edytuj</a>
	| <a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'delete')) . '?id=' . $announcement->ID; ?>">Usuń</a>
	<?php elseif(Zend_Registry::get('userModel')->isAdmin()): ?>
	| <a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'delete')) . '?id=' . $announcement->ID; ?>">Usuń</a>
	<?php endif; ?>
</div>
<?php endforeach; endif; ?>
