<?php
	if(isset($this->message))
		echo $this->message;
	
	$this->stylesheets = array('search.css');
?>

<?php if(count($this->anns) == 0): ?>
Żadne ogłoszenia nie pasują do podanych kryteriów.
<?php endif; ?>

<?php foreach($this->anns as $announcement): ?>
<div class="announcement">
	<img src="<?php echo $this->baseUrl('imgs/' . (count($announcement->images) ? reset($announcement->images) : 'default.png')); ?>" />
	<h1><a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'index')) . '?id=' . $announcement->ID; ?>"><?php echo $announcement->title; ?></a></h1>
	<?php if($announcement->userID == Zend_Registry::get('userModel')->getUserID()): ?>
	<a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'edit')) . '?id=' . $announcement->ID; ?>">Edytuj</a> |
	<a href="<?php echo $this->url(array('controller'=>'announcement', 'action'=>'delete')) . '?id=' . $announcement->ID; ?>">Usuń</a>
	<?php endif; ?>
</div>
<?php endforeach; ?>
